/* SousShift AI value stack data. Prices checked 2026-10-10. low = cheapest published/credible tier, typ = a typical mid tier.
   est: true = the vendor only quotes on request (or it's a freelance service), so the number is a range from the cited guide.
   perLocation: billed or built once per restaurant (doubles for a 2-restaurant owner). count: false = shown, not added to totals.
   Every item lists source ids from SOURCES. Edit numbers here; value.js only renders. */
window.VALUE = {
  vendorCount: 15,
  sources: {
    owner:   { label: "Owner.com pricing (Flexible $249/mo + 5% per order; Flat Rate $499/mo)", url: "https://www.owner.com/pricing", checked: "2026-10-10" },
    chownow: { label: "ChowNow plans and fees (Hub $119/mo, Pro $199–$229/mo), via Sauce", url: "https://www.getsauce.com/post/chownow-pricing-and-fees", checked: "2026-10-10" },
    sqloy:   { label: "Square Loyalty per-location tiers ($45 / $75 / $105 a month), via GetApp", url: "https://www.getapp.com/all-software/a/square-loyalty/", checked: "2026-10-10" },
    toast:   { label: "Toast add-on pricing (Loyalty ~$50–$75/mo, Marketing ~$75/mo), via UpMenu", url: "https://www.upmenu.com/blog/toast-pricing", checked: "2026-10-10" },
    refc:    { label: "ReferralCandy pricing (Basic $9/mo + 10.5% fee; Grow $79/mo + 3.5%)", url: "https://www.referralcandy.com/pricing", checked: "2026-10-10" },
    lbd:     { label: "Leaderboarded plans ($19 / $39 a month, billed yearly)", url: "https://leaderboarded.com/leaderboarded-vs-spinify/", checked: "2026-10-10" },
    spin:    { label: "Spin-to-win widgets (Wheelio ~$15/mo, OptiMonk from $29/mo)", url: "https://www.optimonk.com/wheelio-alternatives", checked: "2026-10-10" },
    seven:   { label: "SevenRooms restaurant CRM, from ~$499/mo (contact sales), via Software Advice", url: "https://www.softwareadvice.com/retail/seven-rooms-profile", checked: "2026-10-10" },
    slick:   { label: "SlickText SMS pricing ($29/mo for 500 texts, $49/mo for 1,000)", url: "https://www.slicktext.com/pricing", checked: "2026-10-10" },
    mc:      { label: "Mailchimp pricing (Essentials $13/mo, Standard $20/mo, entry contact tier)", url: "https://mailchimp.com/pricing/marketing/", checked: "2026-10-10" },
    quo:     { label: "Quo (formerly OpenPhone) missed-call text-back ($15–$19 per user a month)", url: "https://www.quo.com/blog/missed-call-text-back-software/", checked: "2026-10-10" },
    birdeye: { label: "Birdeye Starter ~$299/mo per location (contact sales), via Pabau", url: "https://pabau.com/blog/birdeye-pricing/", checked: "2026-10-10" },
    podium:  { label: "Podium Core ~$399/mo on a 12-month contract (contact sales), via SocialPilot", url: "https://www.socialpilot.co/reviews/blogs/podium-pricing", checked: "2026-10-10" },
    elf:     { label: "Elfsight Instagram Feed pricing (Basic $5–$6/mo)", url: "https://elfsight.com/instagram-feed-instashow/pricing/", checked: "2026-10-10" },
    behold:  { label: "Behold pricing (Starter $10/mo)", url: "https://behold.so/pricing", checked: "2026-10-10" },
    maint:   { label: "Small-business website maintenance ($50–$200/mo), WebsiteSetup", url: "https://websitesetup.org/website-maintenance-costs", checked: "2026-10-10" },
    game:    { label: "Custom HTML5 branded game (advergame) build costs, Dinobros", url: "https://dinobros.com/en/advergames", checked: "2026-10-10" },
    game2:   { label: "Mobile game development cost guide, RetroStyle Games", url: "https://retrostylegames.com/blog/how-much-does-it-cost-to-make-a-mobile-game/", checked: "2026-10-10" },
    photo:   { label: "Food photography pricing ($500–$1,500 a shoot), Format", url: "https://www.format.com/magazine/resources/photography/food-photography-pricing", checked: "2026-10-10" },
    ar:      { label: "AR/3D menu dish models (ARmenu from £49 ≈ $65 a dish), via Petpooja", url: "https://blog.petpooja.com/glossary/ar-menu/", checked: "2026-10-10" },
    trans:   { label: "Professional translation rates ($0.10–$0.18 a word), Milengo", url: "https://milengo.com/knowledge-center/translation-rates-guide/", checked: "2026-10-10" },
    design:  { label: "Graphic design prices (print pieces $75–$225 each), Talo", url: "https://talo.com/costs/graphic-design-prices", checked: "2026-10-10" },
    video:   { label: "Short promo video costs ($500–$2,000 for 30–60 s), Advids", url: "https://advids.co/pricing/how-much-short-promotional-video-creation-cost", checked: "2026-10-10" },
    infl:    { label: "Instagram influencer rates by tier (micro/mid Reels), Influee", url: "https://influee.co/blog/instagram-influencer-pricing", checked: "2026-10-10" },
    slang:   { label: "Slang.ai pricing (Core from $399 per location)", url: "https://www.slang.ai/pricing", checked: "2026-10-10" },
    loman:   { label: "Loman AI phone pricing (~$149–$199/mo, contact sales), via CloudTalk", url: "https://www.cloudtalk.io/blog/loman-ai-pricing/", checked: "2026-10-10" },
    dialz:   { label: "Dialzara SMS Agent ($19/mo + $0.05 per AI message)", url: "https://dialzara.com/solutions/sms-agent", checked: "2026-10-10" }
  },
  items: [
    /* ---- monthly tools ---- */
    { group: "Your app & menu", ic: "📲", name: "Your own branded app, ordering and a QR at every table",
      one: "Guests scan and they're in. No download. Your menu, your colors, table numbers and ordering.",
      tool: "Owner.com or ChowNow", unit: "mo", low: 119, typ: 249, perLocation: true, src: ["chownow", "owner"] },
    { group: "Your app & menu", ic: "📸", name: "4K photo menu with 3D dishes",
      one: "Every dish looks as good as it tastes, and your best plates pop out in 3D.",
      tool: "food photographer + 3D dish models (~10 dishes)", unit: "once", low: 1150, typ: 2500, perLocation: true, est: true, src: ["photo", "ar"] },
    { group: "Your app & menu", ic: "🌎", name: "Menu in 12 languages",
      one: "Tourists and neighbors read your menu in their own language, automatically.",
      tool: "human menu translation, 11 languages", unit: "once", low: 330, typ: 770, perLocation: true, est: true, src: ["trans"] },
    { group: "Rewards that bring them back", ic: "🎁", name: "Points, rewards and visit levels",
      one: "Points on every visit (bar and kitchen can be split), Regular → VIP → Legend levels, and a birthday treat.",
      tool: "Square Loyalty or Toast Loyalty", unit: "mo", low: 45, typ: 75, perLocation: true, est: true, src: ["sqloy", "toast"] },
    { group: "Rewards that bring them back", ic: "🤝", name: "Invite-a-friend referrals",
      one: "Every regular can bring a friend, and you see who brings in the most people.",
      tool: "ReferralCandy (+ a % of referred sales)", unit: "mo", low: 9, typ: 79, perLocation: true, src: ["refc"] },
    { group: "Your own game", ic: "🎮", name: "A custom arcade game made for your restaurant",
      one: "Your food, your logo, you as a cartoon character. Prize scores, Kid and Adult modes.",
      tool: "game studio, one-time build", unit: "once", low: 3000, typ: 8000, perLocation: true, est: true, src: ["game", "game2"] },
    { group: "Your own game", ic: "🏆", name: "Weekly leaderboard, free daily spin and weekly giveaway",
      one: "A reason to open your app every day and come in every week.",
      tool: "spin-to-win + leaderboard widgets", unit: "mo", low: 34, typ: 68, perLocation: true, est: true, src: ["spin", "lbd"] },
    { group: "Your customers", ic: "📇", name: "Your customer list, with sales from the app",
      one: "Every signup's name, phone, birthday and visits. Export to CSV anytime. It's yours.",
      tool: "comes with a loyalty plan; full CRMs like SevenRooms start", unit: "mo", low: 499, typ: 499, perLocation: true, est: true, count: false, src: ["seven"] },
    { group: "Texts & messages", ic: "💬", name: "Text blasts, birthday, \"we miss you\" and holiday specials",
      one: "Your weekly special, birthdays, win-backs and holiday deals go out on their own, only to people who opted in.",
      tool: "SlickText (texts)", unit: "mo", low: 29, typ: 49, perLocation: true, src: ["slick"] },
    { group: "Texts & messages", ic: "✉️", name: "Email to your list",
      one: "The same offers by email, with unsubscribe built in.",
      tool: "Mailchimp", unit: "mo", low: 13, typ: 20, perLocation: true, src: ["mc"] },
    { group: "Texts & messages", ic: "📞", name: "Missed-call text-back",
      one: "Miss a call? They get a text with your app link a few seconds later.",
      tool: "Quo (OpenPhone)", unit: "mo", low: 15, typ: 19, perLocation: true, src: ["quo"] },
    { group: "Texts & messages", ic: "⭐", name: "Google review prompts",
      one: "Happy guests get a nudge to leave you a Google review.",
      tool: "Birdeye or Podium", unit: "mo", low: 299, typ: 399, perLocation: true, est: true, src: ["birdeye", "podium"] },
    { group: "Content & exposure", ic: "📷", name: "Your Instagram feed inside the app",
      one: "Your latest posts show up in the app without you lifting a finger.",
      tool: "Elfsight or Behold", unit: "mo", low: 5, typ: 10, perLocation: true, src: ["elf", "behold"] },
    { group: "Content & exposure", ic: "🖨️", name: "Designer QR print kit",
      one: "Table stickers, a window poster and numbered table cards, plus where to print them.",
      tool: "freelance graphic designer", unit: "once", low: 225, typ: 400, perLocation: true, est: true, src: ["design"] },
    { group: "Content & exposure", ic: "🎬", name: "Promo videos and commercials",
      one: "Short ads for your app and your food, ready to post.",
      tool: "freelance videographer", unit: "once", low: 500, typ: 1250, perLocation: true, est: true, src: ["video"] },
    { group: "Content & exposure", ic: "📣", name: "Exposure on Antidote's food-review audience",
      one: "Antidote's review of your spot plays as a halftime ad in your game, plus a poster and billboard.",
      tool: "one sponsored Reel from a mid-size food creator", unit: "once", low: 1000, typ: 2500, est: true, src: ["infl"] },
    { group: "Setup & support", ic: "🛠️", name: "Setup concierge, hosting and ongoing support",
      one: "We set it all up with you, host it, update menu and prices on request, and answer when you call.",
      tool: "web freelancer maintenance plan", unit: "mo", low: 50, typ: 100, perLocation: true, est: true, src: ["maint"] },
    /* ---- optional, NOT included, NOT in totals ---- */
    { group: "Optional extras (not included, cost extra)", ic: "☎️", name: "AI phone host", optional: true, ours: "$99/mo per location",
      one: "Answers your phone 24/7 when nobody can: hours, menu, specials. Takes messages and texts you.",
      tool: "Slang.ai or Loman", unit: "mo", low: 199, typ: 399, est: true, src: ["loman", "slang"] },
    { group: "Optional extras (not included, cost extra)", ic: "🤖", name: "AI text agent", optional: true, ours: "$49/mo per location",
      one: "Texts guests back 24/7 and sends the reward and come-back texts you approve.",
      tool: "Dialzara SMS Agent at ~1,000 messages", unit: "mo", low: 69, typ: 69, src: ["dialz"] }
  ],
  owners: {
    christian: { who: "Christian", places: "Melody · Nalu Vida", locations: 2, setup: 1500, monthly: 300, back: "../onboarding/christian/",
      lead: "Here's every tool in your package for <b>Melody</b> and <b>Nalu Vida</b>, what you'd pay other companies to get each one on your own, and what you pay us. Your price covers <b>both restaurants</b>.",
      perf: "<b>Performance share:</b> I only win big when you win big. In any month a restaurant's app customers spend more than $3,000 on food and non-alcoholic drinks, I get 10% of those app sales. Each restaurant is counted on its own. Never alcohol, tax or tips, and never your overall sales. <b>90-day results check:</b> if the app isn't bringing back at least 12 tracked return visits a month by day 90, you can cancel the monthly with 30 days' notice. <b>Your customer list is yours</b>, with a full export if you ever leave." },
    jurni: { who: "Jurni", places: "Gritz N Wafflez", locations: 1, setup: 2000, monthly: 300, back: "../onboarding/jurni/",
      lead: "Here's every tool in your package for <b>Gritz N Wafflez</b>, what you'd pay other companies to get each one on your own, and what you pay us.",
      perf: "<b>Performance share:</b> I only win big when you win big. In any month your app customers spend more than $3,000 on food and non-alcoholic drinks, I get 10% of those app sales. Never tax or tips, and never your overall sales. <b>90-day results check:</b> if the app isn't bringing back at least 12 tracked return visits a month by day 90, you can cancel the monthly with 30 days' notice. <b>Your customer list is yours</b>, with a full export if you ever leave." },
    core: { hidden: true, locations: 1, setup: 2000, monthly: 300,
      lead: "Here's every tool in a SousShift AI Core package, what you'd pay other companies to get each one on your own, and what it costs with us.",
      perf: "New agreements include a performance share (10% of app customers' food and non-alcoholic sales, only in months they pass $3,000), a 90-day results check, and a clause that your customer list is yours." }
  }
};
